# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MH_Bayes_Hir_parallel <- function(ref, alt, OPGP, nInd, nSnps, startVal, simPar, seed, nchain, nClust=nchain) {
  cl <- parallel::makeCluster(nClust)
  doParallel::registerDoParallel(cl)
  out <- foreach::foreach(chain = 1:nchain) %dopar% {
    MH_Bayes_Hir(ref, alt, OPGP, nInd, nSnps, startVal[[chain]], simPar, seed+13*chain)
  }
  parallel::stopCluster(cl)
  return(out)
}

MH_Bayes_Hir <- function(ref, alt, OPGP, nInd, nSnps, startVal, simPar, seed)
  .Call(`_BUSMap_MH_Bayes_Hir`, ref, alt, OPGP, nInd, nSnps, startVal, simPar, seed)