# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MH_Bayes_Hir <- function(ref, alt, OPGP, nInd, nSnps, startVal, simPar, seed) {
    .Call(`_BUSMap_MH_Bayes_Hir`, ref, alt, OPGP, nInd, nSnps, startVal, simPar, seed)
}

